#include "../Common.hlsli"

//NOTE(v12.0.0): Unity similar skybox shader (code generated by dear lord savior ChatGPT)
PixelOutput main(PixelInputType aInput)
{
    PixelOutput output;

    const float3 positionDiff = aInput.worldPosition.xyz - cameraPosition;
    const float3 normalizedPositionDiff = normalize(positionDiff);

    // Sample skybox color (using a soft blue tone for the sky)
    const float3 skyColor = float3(0.6f, 0.8f, 1.0f); // Soft blue sky

    // Parameters for horizon blending
    float blendStart = -0.05; // Start blending slightly below the horizon
    float blendEnd = 0.05; // End blending slightly above the horizon

    // Early exit if above the blend region
    if (normalizedPositionDiff.y > blendEnd)
    {
        // Blend between the sky and horizon
        float horizonBlend = smoothstep(blendStart, blendEnd, normalizedPositionDiff.y);
        float3 horizonColor = float3(0.8f, 0.9f, 1.0f); // White-blue for horizon
        output.color = float4(lerp(skyColor, horizonColor, horizonBlend), 1.0f);
        return output;
    }

    // Ground color (grayish tone)
    float groundGradient = smoothstep(-5.0, 0.0, positionDiff.y); // Ground gradient effect
    float3 groundColor = lerp(float3(0.3f, 0.3f, 0.3f), float3(0.5f, 0.5f, 0.5f), groundGradient); // Light gray near ground

    // Horizon blending
    float horizonBlend = smoothstep(blendStart, blendEnd, normalizedPositionDiff.y);
    float3 horizonColor = float3(0.8f, 0.9f, 1.0f); // Light white-blue for horizon

    // Blend between ground and horizon
    float3 blendedColor = lerp(groundColor, horizonColor, horizonBlend);

    // Output the final color
    output.color = float4(blendedColor, 1.0f);
    return output;
}