#pragma once

#define SIMPLE_MAX_BONES 64

#define CONSTANT_BUFFER_SLOT_CAMERA 0
#define CONSTANT_BUFFER_SLOT_OBJECT 1
#define CONSTANT_BUFFER_SLOT_TIME 2
#define CONSTANT_BUFFER_SLOT_LIGHT 3
#define CONSTANT_BUFFER_SLOT_BONES 4

#define TEXTURE_SLOT_ALBEDO 0
#define TEXTURE_SLOT_CUBEMAP 4