#pragma once
#define SIMPLE_MAX_BONES 64

#define CAMERA_CONSTANT_BUFFER_SLOT 0
#define OBJECT_CONSTANT_BUFFER_SLOT 1
#define TIME_CONSTANT_BUFFER_SLOT 2
#define LIGHT_CONSTANT_BUFFER_SLOT 3
#define BONES_CONSTANT_BUFFER_SLOT 4